name: Build APK

on: 
    push:
        branches:
            - 'main'
        tags:
            - 'v*.*.*'

jobs:
    setup_sdk:
        name: Setup SDK
        runs-on: windows-latest

        steps:
            - name: Clone repository
              uses: actions/checkout@v4
              with:
                sparse-checkout: .
                submodules: true

            - name: Setup Flutter SDK
              uses: subosito/flutter-action@v2
              with:
                channel: stable
                flutter-version: 3.22.1
            
            - run: flutter doctor -v

