name: Build APK

on: 
    push:
        branches:
            - 'main'
        tags:
            - 'v*.*.*'

jobs:
    setup_sdk:
        name: Setup SDK
        runs-on: windows-latest

        steps:
            - name: Clone repository
              uses: actions/checkout@v4
              with:
                sparse-checkout: .
                submodules: true

            - name: Setup Android SDK
              uses: android-actions/setup-android@v3
  
            - name: Setup Android NDK
              run: sdkmanager "ndk;23.1.7779620"

            - name: Setup CMake
              run: sdkmanager "cmake;3.22.1"

            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                distribution: 'zulu'
                java-version: '17'

            - name: Setup Flutter SDK
              uses: subosito/flutter-action@v2
              with:
                channel: stable
                flutter-version: 3.22.1

            - run: flutter doctor -v

